name: 🧪 Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:

jobs:
  build-artifact:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: "${{ runner.os }}-nimble-${{ hashFiles('*.nimble', '*.lock') }}"
          restore-keys: |
            ${{ runner.os }}-nimble-

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 2.0.0

      - name: Run Tests
        run: nimble test

